#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
MAX_FD="maximum"

if [ "$cygwin" = "true" -o "$darwin" = "true" -o "$msys" = "true" ] ; then
    ulimit -n 2048 > /dev/null 2>&1
else
    case "$MAX_FD" in
        max*)
            ulimit -H -n 65535 > /dev/null 2>&1
            ulimit -n 65535 > /dev/null 2>&1
        ;;
        *)
            ulimit -n $MAX_FD > /dev/null 2>&1
        ;;
    esac
fi

# Determine the script's directory and set the cwd to the project root.
APP_HOME=$(cd "$(dirname "$0")" && pwd)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Set default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

if [ "$cygwin" = "true" ] ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We build the pattern for arguments to check
    ROOTDIRSRAW=$(find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null)
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
fi

JAVA_CMD=$JAVACMD
if [ -n "$DEFAULT_JVM_OPTS" ] ; then
    JAVA_OPTS="$JAVA_OPTS $DEFAULT_JVM_OPTS"
fi

exec "$JAVA_CMD" $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
